// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// classify_episode_types_cpp
CharacterVector classify_episode_types_cpp(CharacterVector patient_id, NumericVector infection_date, NumericVector last_dose_antibiotic, CharacterVector organism_key, LogicalVector valid);
RcppExport SEXP _peridial_classify_episode_types_cpp(SEXP patient_idSEXP, SEXP infection_dateSEXP, SEXP last_dose_antibioticSEXP, SEXP organism_keySEXP, SEXP validSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type patient_id(patient_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type infection_date(infection_dateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type last_dose_antibiotic(last_dose_antibioticSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type organism_key(organism_keySEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type valid(validSEXP);
    rcpp_result_gen = Rcpp::wrap(classify_episode_types_cpp(patient_id, infection_date, last_dose_antibiotic, organism_key, valid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_peridial_classify_episode_types_cpp", (DL_FUNC) &_peridial_classify_episode_types_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_peridial(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
