# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

classify_episode_types_cpp <- function(patient_id, infection_date, last_dose_antibiotic, organism_key, valid) {
    .Call(`_peridial_classify_episode_types_cpp`, patient_id, infection_date, last_dose_antibiotic, organism_key, valid)
}

